export const Routes = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  Product: "/product/:id",
  Products: "/products",
  Profile: "/profile",
  Cart: "/cart",
  Shipping: "/shipping",
  Payment: "/payment",
  Placeorder: "/placeorder",
  Order: "/order/:id",
  AdminOrderList: "/admin/orderlist",
  AdminProductList: "/admin/productlist",
  AdminUsersList: "/admin/userlist",
};
