export const Routes = {
  Home: "/",
  Login: "/login",
  Register: "/register",
  Search: "/search?/:keyword?",
  Page: "/page?/:pageNumber?",
  Product: "/product/:id",
  Products: "/products",
  Profile: "/profile",
  Cart: "/cart",
  Shipping: "/shipping",
  Payment: "/payment",
  Placeorder: "/placeorder",
  Order: "/order/:id",
  AdminOrderList: "/admin/orderlist",
  AdminProductList: "/admin/productlist",
  AdminUsersList: "/admin/userlist",
};
